### ISSUE TITLE
ResNet prefold activation explained

### ISSUE THREAD

**Issue by chengengliu** [LayerFolding/Layer-Folding#2]
Hi there, I look through both the paper and the code, I noticed that in the paper you mentioned during the prefold phase, when training converges the actions whose å exceed the threshold will be removed. However I only see the threshold in the postfold code but not in the prefold phase. Do I get something wrong? By the way, is the paper submitted to a peer-reviewed journal?

**Comment by LayerFolding** [comment]
Hi,
You are right, it still missing from pre-fold nets.
But, as we show in Fig.5, in our case all α values are either kept around zero or pushed to one.
So in particular - our experiment still is the same even we didn't exceed activation since each α which pushed to one makes the activation linear.

The paper is currently under review.
